// ignore_for_file: public_member_api_docs

import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

import 'package:flutter_deriv_theme/colors.dart';
import 'package:flutter_deriv_theme/text_styles.dart';

/// A class that provides access to theme-related details from anywhere in the
/// app. Through an instance of the [ThemeProvider] class, it is possible to
/// access font family, various app colors, update app theme, and get text style

class ThemeProvider {
  factory ThemeProvider() => _instance;

  ThemeProvider._internal();

  static final ThemeProvider _instance = ThemeProvider._internal();

  final Map<TextStyle, Map<Color, TextStyle>> _textStyle =
      <TextStyle, Map<Color, TextStyle>>{};

  bool _isDarkTheme =
      SchedulerBinding.instance.window.platformBrightness == Brightness.dark;

  bool get isDarkTheme => _isDarkTheme;

  String get fontFamily => TextStyles.appFontFamily;

  Color get brandCoralColor => BrandColors.coral;

  Color get brandGreenishColor => BrandColors.greenish;

  Color get brandOrangeColor => BrandColors.orange;

  Color get accentRedColor =>
      _isDarkTheme ? DarkThemeColors.accentRed : LightThemeColors.accentRed;

  Color get accentGreenColor =>
      _isDarkTheme ? DarkThemeColors.accentGreen : LightThemeColors.accentGreen;

  Color get accentYellowColor => _isDarkTheme
      ? DarkThemeColors.accentYellow
      : LightThemeColors.accentYellow;

  Color get base01Color =>
      _isDarkTheme ? DarkThemeColors.base01 : LightThemeColors.base01;

  Color get base02Color =>
      _isDarkTheme ? DarkThemeColors.base02 : LightThemeColors.base02;

  Color get base03Color =>
      _isDarkTheme ? DarkThemeColors.base03 : LightThemeColors.base03;

  Color get base04Color =>
      _isDarkTheme ? DarkThemeColors.base04 : LightThemeColors.base04;

  Color get base05Color =>
      _isDarkTheme ? DarkThemeColors.base05 : LightThemeColors.base05;

  Color get base06Color =>
      _isDarkTheme ? DarkThemeColors.base06 : LightThemeColors.base06;

  Color get base07Color =>
      _isDarkTheme ? DarkThemeColors.base07 : LightThemeColors.base07;

  Color get base08Color =>
      _isDarkTheme ? DarkThemeColors.base08 : LightThemeColors.base08;

  TextStyle _getStyle({
    @required TextStyle textStyle,
    @required Color color,
  }) {
    ArgumentError.checkNotNull(textStyle, 'textStyle');
    ArgumentError.checkNotNull(color, 'color');

    _textStyle.putIfAbsent(textStyle, () => <Color, TextStyle>{});
    _textStyle[textStyle]
        .putIfAbsent(color, () => textStyle.copyWith(color: color));

    return _textStyle[textStyle][color];
  }

  /// The style of text is generated by calling this function,
  ///
  /// The `type` argument must not be null, and if null is passed, an
  /// ArgumentError will be thrown
  ///
  /// The 'color` may be null or un-passed, in that case, a default value will
  /// be assigned to it
  TextStyle textStyle({
    @required TextStyle textStyle,
    Color color,
  }) {
    ArgumentError.checkNotNull(textStyle, 'textStyle');

    color ??= DarkThemeColors.base01;

    return _getStyle(textStyle: textStyle, color: color);
  }

  void updateTheme({@required Brightness brightness}) =>
      _isDarkTheme = brightness == Brightness.dark;
}
